### ISSUE TITLE
Get Assert Error when bash run_split.sh

### ISSUE THREAD

**Issue by zlpiscoming** [fuxiAIlab/RL4RS#8]
Hi, I run your code and get 

Traceback (most recent call last):
  File "data_preprocess.py", line 179, in <module>
    dataset2tfrecord(config, file, out_file, is_slate=False)
  File "data_preprocess.py", line 149, in dataset2tfrecord
    samples = feature_construct(tmp, is_slate)
  File "data_preprocess.py", line 97, in feature_construct
    assert sequence_id - 1 == i
AssertionError

When I run bash run_split.sh, How can I solve it and Why I get it?
Thanks

**Comment by fuxiupresearch** [comment]
You can modify the code to "assert sequence_id -1==i, session" to print the session to enrich the error message
Or more directly, 
`if sequence_id-1!=i:  
    break`
